### PR TITLE
major improvements in UI, improve UX

### PR DESCRIPTION
**Pull request by tusharnankani**
## What is the change?

This PR includes:

- Switched to a more readable font.
- navbar changes
  - add transitions
  - remove background hover
  - improve color coordination

https://user-images.githubusercontent.com/61280281/103529001-ec40ab00-4eaa-11eb-8f12-321e0fb1ea7d.mp4

- footer changes
  - increase padding
  - improve hover effect
  - minor fix of `mailto`

https://user-images.githubusercontent.com/61280281/103529000-eba81480-4eaa-11eb-829f-f584bf599cf6.mp4

- Card changes:
  - add box-shadow to the card
  - add transition when hovered on courses
  - change gif images layout to circular
  - improve the user experience 

https://user-images.githubusercontent.com/61280281/103528986-e8148d80-4eaa-11eb-9f25-93bb0f17b624.mp4

## Related issue?

In reference to #4 

## Files edited?

- `views/partials/header.ejs`
- `views/partials/footer.ejs`
- `public/css/index.js`

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes like this (`[x]`).

- [X] I've checked there aren't other open [Pull Requests](https://github.com/inaxia/hashcode_web/pulls) for the same update/change?
- [ ] I've made corresponding changes to the documentation?
- [X] My submission doesn't break any existing feature.
- [X] I've tested this code locally before submission?

@Nishant2907

### CODE REVIEW

**Comment by tusharnankani** [comment]
@Nishant2907 any updates?

**Review by Nishant2907 — APPROVED** [review]
Reviewed and look good to me.

**Comment by Nishant2907** [comment]
@tusharnankani, there are some conflicts in the `index.css` file. Kindly resolve it.

**Comment by tusharnankani** [comment]
> @tusharnankani, there are some conflicts in the `index.css` file. Kindly resolve it.

Fixed.

**Review by Nishant2907 — APPROVED** [review]
Everything works fine.

**Pull request merged**
