### PR TITLE
add glassmorphism to landing page

### PR DESCRIPTION
**Pull request by tusharnankani**
## What is the change?

Added Glassmorphism to the landing page.

## Related issue?

In reference to #4 

## Files edited?

- `views/partials/header.ejs`
- `public/css/index.js`

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes like this (`[x]`).

- [X] I've checked there aren't other open [Pull Requests](https://github.com/inaxia/hashcode_web/pulls) for the same update/change?
- [ ] I've made corresponding changes to the documentation?
- [X] My submission doesn't break any existing feature.
- [X] I've tested this code locally before submission?

## Current behavior

https://user-images.githubusercontent.com/61280281/103520072-95cc7000-4e9c-11eb-9c35-05698e04ae18.mp4

@Nishant2907

### CODE REVIEW

**Comment by Nishant2907** [comment]
looks good to me, it will be great if you can work on the courses card sections and on the footer too.
Any ideas on those sections will be appreciated.

**Comment by tusharnankani** [comment]
Yes, I will create atomic separate PRs for the footer and navbar.

**Comment by tusharnankani** [comment]
@Nishant2907 any updates?

**Review by Nishant2907 — APPROVED** [review]
Looks fine.

**Pull request merged**
