### PR TITLE
Updated the UI of readmefile

### PR DESCRIPTION
**Pull request by danish1804**
## HTML PART APPLICATION
    <a href="#">website title image</a>	<!DOCTYPE html>
    <h2 align="center">discover best courses for the best  learning</h2>	<html lang="en" dir="ltr">
</p>	  <head>
    <meta charset="utf-8">

**linking the CSS part With HTML Part**      
    <link rel="stylesheet" href="FIRST.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">

**Adding Fonts from google**    
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital@1&display=swap" rel="stylesheet">

   <title>project</title>
  </head>
  <body>

**Working with the body** 
    <h1>HASHCODE</h1>
    <h2>discover best courses for the best learning!!</h2>

**added main focus of the project** 
    <p>This project is build to make coding knowledge available to every place through an app and a website. This is an online platform to learn different languages from the best hand-picked courses
    </p>

**Adding An extra Line for clear info**    
    <p>This course provides you with the following Courses:</p>

**Making the picture more responsive by clicking on them we are directed to the respective page**
    <table class="courses">
      <tr>

**For HTML IMAGE**          
        <td>
          <a href="https://html.com/">
            Html
          </a>
        </td>
**For CSS IMAGE**        
        <td>
          <a href="https://www.w3.org/Style/CSS/Overview.en.html">
            CSS
          </a>
        </td>
**For JAVASCRIPT IMAGE**        
        <td>
          <a href="https://www.javascript.com/">
            JavaScript
          </a>
        </td>
      </tr>

    </table>

  </body>
</html>

## APPLICATION OF THE **CSS** PART TO BE USED IN **HTML** FOR BETTER STYLING AND BACKGROUND TO BE USED IN THE ABOVE CODE
body{
  font-family: 'Open Sans', sans-serif;
 **Added background for the whole page** 
  background-color: #011627;
  color: #FDFFFC;
  align: center;
  text-align: center;

  **Added borders**
  border: 20px solid #2EC486;

  padding-bottom: 350px;

}

h1{
  font-size: 4.0em;
}

.courses{
  margin: auto;
}

**adding detail in the pictures used from the internet for a redirecting page**
 #a{
   height: 150px;
   width:  300px;
   padding: 10px;

 }
 #b{
   height: 150px;
   width:  300px;
   padding: 10px;

 }
 #c{
   height: 150px;
   width:  300px;
   padding: 10px;

 }

``

### CODE REVIEW

**Comment by danish1804** [comment]
image

**Comment by danish1804** [comment]
Thanks for your help @Nishant2907 @Hardikkr for the suggestion,
can you please review this PR

**Comment by Nishant2907** [comment]
@danish1804, as i can see you have added the HTML code in the readme file. But it should not be there. Go to the `index.ejs` and do the necessary HTML updates there. and then add the css files in the respective css files. Do these things then add a PR .

**Comment by Nishant2907** [comment]
Closing the PR due to inactivity.

**Pull request closed without merging**
